//
//  VoiceSampleText.swift
//  TextAloudKit
//
//  Created by Gavin Henderson on 27/04/2023.
//



public let voiceSampleText = [

    "af":"Hallo, ek is jou nuwe praatstem. Hoe klink ek?",
    "am":"ጤና ይስጥልኝ ፣ እኔ አዲሱ ተናጋሪ ድምጽህ ነኝ። እንዴት ነው የምሰማው?",
    "ar":"مرحبا، أنا صوتك الناطق الجديد. كيف أبدو ؟",
    "az":"Salam, mən sizin yeni danışan səsinizəm. Necə səslənə bilərəm?",
    "bg":"Здравейте, аз съм новият ви глас. Как ти звуча?",
    "bn":"হ্যালো, আমি আপনার নতুন কথা বলার ভয়েস. আমি কেমন শব্দ করব?",
    "bs":"Zdravo, ja sam tvoj novi glas. Kako zvučim?",
    "ca":"Hola, sóc la teva nova veu. Com puc sonar?",
    "cs":"Dobrý den, jsem váš nový mluvčí. Jak to zní?",
    "cy":"Helo, fi yw eich llais siarad newydd. Sut ydw i&#39;n swnio?",
    "da":"Hej, jeg er din nye stemme. Hvordan lyder jeg?",
    "de":"Hallo, ich bin deine neue sprechende Stimme. Wie höre ich mich an?",
    "el":"Γεια σας, είμαι η νέα σας ομιλούσα φωνή. Πώς ακούγομαι;",
    "en":"Hello, I am your new speaking voice. How do I sound?",
    "es":"Hola, soy tu nueva voz. ¿Cómo sueno?",
    "et":"Tere, mina olen teie uus häälekandja. Kuidas ma kõlan?",
    "eu":"Kaixo, zure ahots berria naiz. Nola egiten dut soinua?",
    "fa":"سلام من صدای جدید شما هستم چگونه صدا کنم؟",
    "fi":"Hei, olen uusi puhuva äänesi. Miltä kuulostan?",
    "fr":"Bonjour, je suis votre nouvelle voix parlante. Comment ça sonne ?",
    "ga":"Dia duit, is mise do ghuth labhartha nua. Conas is féidir liom fuaime?",
    "gl":"Ola, son a túa nova voz que fala. Como soo?",
    "gu":"હેલો, હું તમારો નવો બોલવાનો અવાજ છું. હું કેવી રીતે અવાજ કરું?",
    "he":"שלום, אני הקול המדבר החדש שלך. איך אני נשמע?",
    "hi":"नमस्ते, मैं आपकी नई बोलती आवाज़ हूँ। मैं कैसे आवाज करूँ?",
    "hr":"Zdravo, ja sam tvoj novi glas. Kako zvučim?",
    "hu":"Helló, én vagyok az új hangod. Hogy hangzik?",
    "hy":"Բարև ձեզ, ես ձեր նոր խոսող ձայնն եմ: Ինչպե ՞ ս եմ ես հնչում:",
    "id":"Halo, saya suara berbicara baru Anda. Bagaimana kedengarannya?",
    "is":"Halló, ég er nýja röddin þín. Hvernig hljóma ég?",
    "it":"Ciao, sono la tua nuova voce parlante. Come ti sembro?",
    "ja":"こんにちは、私はあなたの新しい話し声です。どのように聞こえますか？",
    "jv":"'JV' IS AN INVALID TARGET LANGUAGE . EXAMPLE: LANGPAIR=EN|IT USING 2 LETTER ISO OR RFC3066 LIKE ZH-CN. ALMOST ALL LANGUAGES SUPPORTED BUT SOME MAY HAVE NO CONTENT",
    "ka":"Ჱეპაგჲ, £ აჟ ჟსმ რგჲ £ ჲრ ნჲგ დლაჟ. კაკ ჱგსფთ?",
    "kk":"Сәлем, мен сіздің жаңа сөйлейтін дауысыңызбын. Мен қалай дыбыстаймын?",
    "km":"សួស្តី ខ្ញុំជាសំឡេងនិយាយថ្មីរបស់អ្នក។ តើខ្ញុំបញ្ចេញសំឡេងយ៉ាងដូចម្តេច?",
    "kn":"ಹಲೋ, ನಾನು ನಿಮ್ಮ ಹೊಸ ಮಾತನಾಡುವ ಧ್ವನಿ. ನಾನು ಹೇಗೆ ಧ್ವನಿಸಲಿ?",
    "ko":"안녕하세요, 저는 여러분의 새로운 발성입니다. 어떻게 들리나요?",
    "lo":"ສະບາຍດີ, ຂ້ອຍເປັນສຽງເວົ້າໃໝ່ຂອງເຈົ້າ. ຂ້ອຍຈະອອກສຽງແນວໃດ?",
    "lt":"Sveiki, aš esu jūsų naujas kalbantis balsas. Kaip aš skambu?",
    "lv":"Labdien, es esmu jūsu jaunā runājošā balss. Kā es varu izklausīties?",
    "mk":"Здраво, јас сум твојот нов говорник. Како ти звучам?",
    "ml":"ഹലോ, ഞാൻ നിങ്ങളുടെ പുതിയ സംസാരിക്കുന്ന ശബ്ദമാണ്. ഞാൻ എങ്ങനെ ശബ്ദിക്കും?",
    "mn":"Сайн байна уу, би таны шинэ дуу хоолой байна. Би яаж дуугардаг вэ?",
    "mr":"नमस्कार, मी तुमचा नवीन बोलणारा आवाज आहे. मी कसा आवाज करू?",
    "ms":"Hello, saya suara baru anda bercakap. Bagaimana bunyinya?",
    "mt":"Ħelow, jiena l-vuċi l-ġdida tiegħek li titkellem. Kif nista 'nħoss?",
    "my":"ဟယ်လို၊ ငါက မင်းရဲ့စကားပြောသံအသစ်ပါ။ ငါဘယ်လိုအသံလဲ။",
    "nb":"Hei, jeg er din nye stemme. Hvordan høres jeg ut?",
    "ne":"नमस्ते, म तपाईंको नयाँ बोल्ने आवाज हुँ। म कसरी आवाज गर्छु?",
    "nl":"Hallo, ik ben uw nieuwe sprekende stem. Hoe klink ik?",
    "pl":"Witaj, jestem twoim nowym głosem. Jak brzmię?",
    "ps":"سلام، زه ستاسو نوی غږ یم. زه څنګه غږ وکړم؟",
    "pt":"Olá, eu sou a sua nova voz falante. Como é que eu pareço?",
    "ro":"Bună ziua, eu sunt noua ta voce vorbitoare. Cum ți se pare?",
    "ru":"Здравствуйте, я ваш новый говорящий голос. Как я звучу?",
    "si":"හෙලෝ, මම ඔබේ නව කතා කරන හඬයි. මම ශබ්ද කරන්නේ කෙසේද?",
    "sk":"Dobrý deň, som váš nový hovoriaci hlas. Ako to znie?",
    "sl":"Pozdravljeni, jaz sem vaš novi govoreči glas. Kako zvenim?",
    "so":"Hello, waxaan ahay codkaaga cusub ee ku hadlaya. Sideen u dhawaaqaa?",
    "sq":"Përshëndetje, unë jam zëri juaj i ri. Si të tingëlloj?",
    "sr":"Zdravo, ja sam tvoj novi glas. Kako zvučim?",
    "su":"Halo, kuring sora omongan anyar anjeun. Kumaha sora kuring?",
    "sv":"Hej, jag är din nya talande röst. Hur låter jag?",
    "sw":"Hello, mimi ni sauti yako mpya ya kuzungumza. Ninapaza sauti vipi?",
    "ta":"வணக்கம், நான் உங்கள் புதிய பேசும் குரல். நான் எப்படி ஒலிப்பது?",
    "te":"హలో, నేను మీ కొత్త మాట్లాడే వాయిస్. నేను ఎలా ధ్వనించగలను?",
    "th":"สวัสดีฉันเป็นเสียงพูดใหม่ของคุณฉันจะทำเสียง?",
    "tr":"Merhaba, ben senin yeni konuşan sesinim. Kulağa nasıl geliyor?",
    "uk":"Привіт, я твій новий голос. Як я звучу?",
    "ur":"ہیلو، میں آپ کی نئی بولنے والی آواز ہوں۔ میں کیسے آواز دیتا ہوں؟",
    "uz":"Salom, men sizning yangi gapiradigan ovozingizman. Men qanday ovoz beraman?",
    "vi":"Xin chào, tôi là giọng nói mới của bạn. Tôi nghe thế nào?",
    "zh":"你好，我是你的新声音。我听起来怎么样？",
    "zu":"Sawubona, ngiyizwi lakho elisha lokukhuluma. Ngizwakala kanjani?",

]
